eureka:
  client:
    register-with-eureka: false
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: games-service
          uri: http://localhost:8090
          predicates:
            - Path=/games/**
  application:
    name: gateway-service
server:
  port: 8222